
SimpleSkeletonRevisited: SimpleSkeletonRevisited.o
	g++ SimpleSkeletonRevisited.o -lOpenNI -o SimpleSkeletonRevisited

SimpleSkeletonRevisited.o: SimpleSkeletonRevisited.cpp
	g++ SimpleSkeletonRevisited.cpp -I /usr/include/ni -c -o SimpleSkeletonRevisited.o

